### PR TITLE
fix: possibly wrong argc/argv

### LINKED ISSUE #23: Wrong argc/argv in debug target
Original discussion: https://github.com/nervosnetwork/capsule/issues/72

### PR DESCRIPTION
**Pull request by blckngm**
Use `global_asm` to define `_start` so that it definitely does not have function prologue which may alter the `sp` register.

Fix #23.

### CODE REVIEW

**Comment by TheWaWaR** [comment]
Can you provide a test case that in debug mode read argc/argv will not work, since the test case in `ckb-std` works just fine.
https://github.com/nervosnetwork/ckb-std/blob/01a6b1bb9593760a9b956f3a12764f83492c9a0a/contracts/exec-callee/src/entry.rs#L11

**Comment by blckngm** [comment]
The current approach happens to work. But it might break after compiler upgrade or under different compile options. The `global_asm` approach is guaranteed to work.

**Comment by jjyr** [comment]
@mohanson

File: src/entry.rs [hunk 1]
```diff
@@ -17,25 +19,30 @@ macro_rules! entry {
...
+            panic!("ckb_std::entry is only valid for riscv64 target")
         }
 
+        // Use global_asm so the compiler won't insert function prologue in _start.
+        #[cfg(target_arch = "riscv64")]
+        core::arch::global_asm!(
+            ".global _start",
+            "_start:",
+            // Argc.
+            "lw a0, 0(sp)",
```
Comment (mohanson) [inline src/entry.rs:49]: argc is 64-bit size, should use `ld` instead

File: src/entry.rs [hunk 2]
```diff
@@ -17,25 +19,30 @@ macro_rules! entry {
...
+            // Argv.
+            "addi a1, sp, 8",
+            // Envp.
+            "li a2, 0",
```
Comment (mohanson) [inline src/entry.rs:53]: What is the purpose of setting a2 = 0?

Comment (blckngm) [reply src/entry.rs:53]: Copied from original code, which seems to be copied from assembly generated by compiling C code.

Comment (mohanson) [reply src/entry.rs:53]: It's weird, but if the code works, leave it as it is.

Comment (blckngm) [reply src/entry.rs:53]: Yeah, it's envp:

https://github.com/riscvarchive/riscv-newlib/blob/f289cef6be67da67b2d97a47d6576fa7e6b4c858/libgloss/riscv/crt0.S#L51-L53

File: src/entry.rs (hunk 1 above)
Comment (blckngm) [reply src/entry.rs:49]: I think it's actually 32-bit, because in C `argc` is `int`(on riscv, `i32`).

I will change the example main function signature to take `argc: c_int` for clarity.

Comment (mohanson) [reply src/entry.rs:49]: great

File: contracts/exec-callee/src/entry.rs [hunk 3]
```diff
@@ -3,26 +3,22 @@ use core::result::Result;
...
 use core::slice::from_raw_parts;
 
 use crate::error::Error;
 
-pub fn main(argc: u64, argv: *const *const u8) -> Result<(), Error> {
-    let args = unsafe { from_raw_parts(argv, argc as usize) };
+pub unsafe fn main(
+    argc: core::ffi::c_int,
+    argv: *const *const core::ffi::c_char,
+) -> Result<(), Error> {
```
Comment (TheWaWaR) [inline contracts/exec-callee/src/entry.rs:14]: I think mark `main` as unsafe is not a good idea, since user may call an unsafe function just like `from_raw_parts` and the the call is not marked as `unsafe`, user may neglect those unsafe calls.

Comment (blckngm) [reply contracts/exec-callee/src/entry.rs:14]: This function is `unsafe` because it deferences raw pointers and is `pub`.

If it's not marked unsafe, you can have another safe rust function calling it with invalid pointers leading to UB. Safe rust should not cause UB, so this function has to be unsafe.

Comment (blckngm) [reply contracts/exec-callee/src/entry.rs:14]: An alternative design is to provide a safe `args` API, maybe similar to `std::env::{args, args_os}`, so users don't need to deal with raw pointers.

Comment (blckngm) [reply contracts/exec-callee/src/entry.rs:14]: See https://github.com/nervosnetwork/ckb-std/pull/26. WDYT?

Comment (TheWaWaR) [reply contracts/exec-callee/src/entry.rs:14]: > If it's not marked unsafe, you can have another safe rust function calling it with invalid pointers leading to UB. Safe rust should not cause UB, so this function has to be unsafe.

I don't understand where the `UB` comes from, can you point it out explicitly?

Comment (blckngm) [reply contracts/exec-callee/src/entry.rs:14]: See https://doc.rust-lang.org/nomicon/safe-unsafe-meaning.html

> On functions, unsafe means that users of the function must check that function's documentation to ensure they are using it in a way that maintains the contracts the function requires.
>
> **No matter what, Safe Rust can't cause Undefined Behavior.**

If this function is not marked unsafe, you can have safe rust code like

```
main(2, core::ptr::null());
```

causing UB.

Comment (blckngm) [reply contracts/exec-callee/src/entry.rs:14]: What you want is probably `#[deny(unsafe_op_in_unsafe_fn)]`.
